/** User-facing strings for payment links. Short on purpose: labels, not paragraphs. */
import type { LinkStatus, PayMethod, UnavailableReason } from "@/lib/api/links";
import type { StepId } from "./errors";

export const LINKS_COPY = {
  listTitle: "Payment links",
  newLink: "New link",
  emptyTitle: "No links yet.",
  emptyBody: "Create one and share it anywhere.",
  emptyFiltered: "No links in this state.",
  untitled: "Untitled link",
  customerSets: "Customer sets",
  columns: { title: "Link", status: "Status", amount: "Amount", uses: "Uses", url: "Short link", created: "Created" },
  tabs: { all: "All", active: "Active", draft: "Drafts", paused: "Paused", archived: "Archived" } as Record<"all" | LinkStatus, string>,

  builder: {
    newTitle: "New payment link",
    settings: "Link settings",
    preview: "Preview",
    edit: "Edit",
    view: "Show",
    saving: "Saving",
    saved: "Saved",
    unsaved: "Unsaved changes",
    notSaved: "Not saved",
    notStarted: "Draft saves as you type",
    save: "Save changes",
    publish: "Publish",
    resume: "Resume",
    pause: "Pause",
    archive: "Archive",
    duplicate: "Duplicate",
    deleteDraft: "Delete draft",
    cancel: "Cancel",
    expandAll: "Expand all",
    collapseAll: "Collapse all",
    duplicateToChange: "Duplicate to change",
    locked: "Live links keep their price, currency, methods and fees.",
    fixErrors: (n: number) => (n === 1 ? "Fix 1 field to publish." : `Fix ${n} fields to publish.`),
    archiveConfirm: "Archive this link? It stops taking payments for good.",
    deleteConfirm: "Delete this draft?",
    published: "Link published",
    resumed: "Link resumed",
  },

  steps: {
    item: { title: "Item" },
    customer: { title: "Customer" },
    payment: { title: "Payment" },
    after: { title: "After payment" },
    settlement: { title: "Settlement" },
    lifecycle: { title: "Lifecycle and look" },
  } satisfies Record<StepId, { title: string }>,

  summary: {
    items: (n: number) => (n === 1 ? "1 item" : `${n} items`),
    noContact: "No contact fields",
    singleUse: "Single use",
    noMethods: "No methods",
    fees: (who: string) => `fees: ${who}`,
    noEnd: "No end date",
    ends: (when: string) => `Ends ${when}`,
  },

  fields: {
    title: "Title",
    description: "Description",
    amountMode: "Amount",
    modes: { fixed: "Fixed", customer: "Customer sets", line_items: "Line items" },
    amount: "Price",
    currency: "Currency",
    chooseCurrency: "Choose",
    notEnabled: "not enabled here",
    min: "Minimum",
    max: "Maximum",
    lineItems: "Line items",
    itemName: "Item",
    qty: "Qty",
    unitPrice: "Unit price",
    taxRate: "Tax %",
    addItem: "Add item",
    removeItem: (n: number) => `Remove item ${n}`,
    reference: "Reference",
    category: "Category",
    metadata: "Metadata",
    addMetadata: "Add field",
    removeMetadata: (n: number) => `Remove field ${n}`,
    key: "Key",
    value: "Value",
    customerFields: { name: "Name", email: "Email", phone: "Phone" },
    fieldModes: { required: "Required", optional: "Optional", hidden: "Hidden" },
    prefill: "Prefill",
    prefillExamples: { name: "Ada Lovelace", email: "name@example.com", phone: "+14155550123" },
    billing: "Billing address",
    shipping: "Shipping address",
    questions: "Questions",
    addQuestion: "Add question",
    removeQuestion: (n: number) => `Remove question ${n}`,
    questionKey: "Key",
    questionLabel: "Question",
    questionType: "Type",
    questionTypes: { text: "Text", select: "Select", checkbox: "Checkbox" },
    options: "Options, one per line",
    required: "Required",
    perOrder: "Ask every payment",
    multiUse: "Multiple payments",
    useLimit: "Payment limit",
    expiresAfter: "Ends after",
    limitsHint: "The link stops at whichever limit comes first.",
    methods: "Methods",
    methodNames: { card: "Card", upi: "UPI", bank: "Bank transfer", crypto: "Crypto" } satisfies Record<PayMethod, string>,
    noOptions: "No payment methods are enabled in this environment.",
    noOptionsForCurrency: (c: string) => `No methods are enabled for ${c}.`,
    chooseCurrencyFirst: "Choose a currency to see methods.",
    capture: "Card capture",
    captureModes: { automatic: "Capture now", manual: "Authorise only" },
    threeDS: "3DS",
    threeDSModes: { inherit: "Account default", force: "Always" },
    tolerance: "Amount tolerance (bps)",
    quoteExpiry: "Quote valid (seconds)",
    feeBearer: "Fees paid by",
    bearers: { merchant: "You", customer: "Customer" },
    success: "On success",
    successModes: { message: "Show message", redirect: "Redirect" },
    successMessage: "Message",
    successUrl: "Redirect URL",
    successUrlHint: "We add ?reference_id= to it",
    receipt: "Email receipt",
    receiptNote: "Receipt note",
    webhook: "Webhook",
    noWebhook: "None",
    failureRetry: "Allow retry",
    failureMessage: "Failure message",
    settlement: "Settle to",
    settlementModes: { default: "Account default", fiat: "Bank", crypto: "Wallet" },
    destination: "Destination ID",
    chain: "Chain",
    asset: "Asset",
    holdInAsset: "Hold in asset",
    holdNote: "Funds stay in the asset and move with its price.",
    timing: "Timing",
    timingModes: { cycle: "Next cycle", immediate: "When paid" },
    expiresAt: "Ends on",
    logo: "Logo URL",
    accent: "Accent colour",
    accentPicker: "Pick accent colour",
    noAccent: "None",
    language: "Language",
  },

  fee: {
    rule: (id: number, version: number) => `Rule ${id} v${version}`,
    fee: "Fee",
    tax: "Tax",
    net: "You receive",
    total: "Customer pays",
    onMinimum: "Priced on the minimum",
    pending: "Priced after save",
    noAmount: "Add an amount to see fees",
    atPayTime: "Priced at pay time",
    refused: {
      method_no_fee_rule: "No fee rule. Cannot publish.",
      method_no_connector: "No connector here. Cannot publish.",
      surcharge_forbidden: "Customer fees not allowed",
      surcharge_needs_quote: "Customer fees need a quote. Not available yet.",
      fee_exceeds_amount: "Fee exceeds amount",
      fee_rule_ambiguous: "Fee rules tie. Ask an admin.",
      method_unavailable: "Pricing unavailable",
    } as Record<string, string>,
  },

  detail: {
    qr: "QR code",
    uses: "Uses",
    published: "Published",
    copy: "Copy link",
    copied: "Link copied",
  },

  checkout: {
    region: "Checkout preview",
    device: { label: "Device", desktop: "Desktop", phone: "Phone" },
    tabs: { pay: "Checkout", done: "Done" },
    updating: "Updating",
    paused: "Fix the highlighted fields to update the preview.",
    failed: "Preview unavailable.",
    customerAmount: "Amount",
    addCurrency: "Add a currency",
    contact: "Contact",
    contactLabels: { name: "Name", email: "Email", phone: "Phone" },
    billing: "Billing address",
    shipping: "Shipping address",
    payWith: "Pay with",
    amount: "Amount",
    fee: "Fee",
    feeTax: "Tax on fee",
    tax: "Tax",
    subtotal: "Subtotal",
    totalDue: "Total due",
    pay: "Pay",
    optional: "optional",
    ends: "Ends",
    from: "From",
    upTo: "Up to",
    to: "to",
    paid: "Payment received",
    redirect: "Customer returns to your site",
    receipt: "Receipt sent by email",
    untitled: "Untitled",
    noMethods: "No payment methods yet",
    unavailable: {
      paused: "This link is paused.",
      expired: "This link has expired.",
      use_limit_reached: "This link has reached its limit.",
      no_methods_available: "No way to pay yet. Add a method.",
    } satisfies Record<UnavailableReason, string>,
  },
} as const;

export function methodLabel(m: { method: PayMethod; chain?: string | null; asset?: string | null }): string {
  if (m.method === "crypto") return [m.asset, m.chain ? `on ${m.chain}` : ""].filter(Boolean).join(" ") || "Crypto";
  return LINKS_COPY.fields.methodNames[m.method];
}
