/** User-facing strings for payment links. Short on purpose: labels, not paragraphs. */
import type { LinkStatus, PayMethod, UnavailableReason } from "@/lib/api/links";
import type { StepId } from "./errors";

export const LINKS_COPY = {
  nav: "Links",
  listTitle: "Payment links",
  newLink: "New link",
  emptyTitle: "No links yet.",
  emptyBody: "Create one and share it anywhere.",
  emptyFiltered: "No links in this state.",
  untitled: "Untitled link",
  customerSets: "Customer sets",
  columns: { title: "Link", status: "Status", amount: "Amount", uses: "Uses", url: "Short link", created: "Created" },
  tabs: { all: "All", active: "Active", draft: "Drafts", paused: "Paused", archived: "Archived" } as Record<"all" | LinkStatus, string>,

  builder: {
    newTitle: "New payment link",
    settings: "Link settings",
    preview: "Preview",
    edit: "Edit",
    saving: "Saving",
    saved: "Saved",
    unsaved: "Unsaved changes",
    notSaved: "Not saved",
    save: "Save changes",
    publish: "Publish",
    resume: "Resume",
    pause: "Pause",
    archive: "Archive",
    duplicate: "Duplicate",
    deleteDraft: "Delete draft",
    duplicateToChange: "Duplicate to change",
    locked: "Live links keep their price, currency and methods.",
    fixErrors: (n: number) => (n === 1 ? "Fix 1 field to continue." : `Fix ${n} fields to continue.`),
    archiveConfirm: "Archive this link? It stops taking payments for good.",
    deleteConfirm: "Delete this draft?",
  },

  steps: {
    item: { title: "Item", hint: "What is being paid for" },
    customer: { title: "Customer", hint: "Who is paying" },
    payment: { title: "Payment", hint: "How they can pay" },
    after: { title: "After payment", hint: "Success, receipt, webhook" },
    settlement: { title: "Settlement", hint: "Where the money goes" },
    lifecycle: { title: "Lifecycle and look", hint: "Expiry and branding" },
  } satisfies Record<StepId, { title: string; hint: string }>,

  fields: {
    title: "Title",
    description: "Description",
    amountMode: "Amount",
    modes: { fixed: "Fixed", customer: "Customer sets", line_items: "Line items" },
    amount: "Price",
    currency: "Currency",
    min: "Minimum",
    max: "Maximum",
    lineItems: "Line items",
    itemName: "Item",
    qty: "Qty",
    unitPrice: "Unit price",
    taxRate: "Tax %",
    addItem: "Add item",
    reference: "Reference",
    category: "Category",
    metadata: "Metadata",
    addMetadata: "Add field",
    key: "Key",
    value: "Value",
    customerFields: { name: "Name", email: "Email", phone: "Phone" },
    fieldModes: { required: "Required", optional: "Optional", hidden: "Hidden" },
    prefill: "Prefill",
    billing: "Billing address",
    shipping: "Shipping address",
    questions: "Questions",
    addQuestion: "Add question",
    questionKey: "Key",
    questionLabel: "Question",
    questionType: "Type",
    questionTypes: { text: "Text", select: "Select", checkbox: "Checkbox" },
    options: "Options, one per line",
    required: "Required",
    perOrder: "Ask every payment",
    multiUse: "Multiple payments",
    useLimit: "Payment limit",
    methods: "Methods",
    methodNames: { card: "Card", upi: "UPI", bank: "Bank transfer", crypto: "Crypto" } satisfies Record<PayMethod, string>,
    addCrypto: "Add asset",
    chain: "Chain",
    asset: "Asset",
    capture: "Card capture",
    captureModes: { automatic: "Capture now", manual: "Authorise only" },
    threeDS: "3DS",
    threeDSModes: { inherit: "Account default", force: "Always" },
    tolerance: "Amount tolerance (bps)",
    quoteExpiry: "Quote valid (seconds)",
    feeBearer: "Fees paid by",
    bearers: { merchant: "You", customer: "Customer" },
    success: "On success",
    successModes: { message: "Show message", redirect: "Redirect" },
    successMessage: "Message",
    successUrl: "Redirect URL",
    receipt: "Email receipt",
    receiptNote: "Receipt note",
    webhook: "Webhook",
    noWebhook: "None",
    failureRetry: "Allow retry",
    failureMessage: "Failure message",
    settlement: "Settle to",
    settlementModes: { default: "Account default", fiat: "Bank", crypto: "Wallet" },
    destination: "Destination ID",
    holdInAsset: "Hold in asset",
    holdNote: "Funds stay in the asset and move with its price.",
    timing: "Timing",
    timingModes: { cycle: "Next cycle", immediate: "When paid" },
    expiresAt: "Ends on",
    expiresAfter: "Ends after payments",
    logo: "Logo URL",
    accent: "Accent colour",
    language: "Language",
  },

  fee: {
    rule: (id: number, version: number) => `Rule ${id} v${version}`,
    fee: "Fee",
    tax: "Tax",
    net: "You receive",
    total: "Customer pays",
    noAmount: "Add an amount to see fees",
    atPayTime: "Priced at pay time",
    loading: "Pricing",
    refused: {
      no_fee_rule: "No fee rule. Cannot publish.",
      surcharge_forbidden: "Surcharge not allowed",
      fee_exceeds_amount: "Fee exceeds amount",
    } as Record<string, string>,
  },

  detail: {
    link: "Link",
    qr: "QR code",
    uses: "Uses",
    published: "Published",
    environment: "Mode",
  },

  checkout: {
    device: { desktop: "Desktop", phone: "Phone" },
    tabs: { pay: "Checkout", done: "Done" },
    customerAmount: "Amount",
    range: (min: string | null, max: string | null, cur: string) =>
      min && max ? `${min} to ${max} ${cur}` : min ? `From ${min} ${cur}` : max ? `Up to ${max} ${cur}` : "",
    contact: "Contact",
    billing: "Billing address",
    shipping: "Shipping address",
    payWith: "Pay with",
    fee: "Fee",
    feeTax: "Tax on fee",
    totalDue: "Total due",
    pay: "Pay",
    optional: "Optional",
    ends: "Ends",
    paid: "Payment received",
    redirect: "Customer returns to your site",
    receipt: "Receipt sent by email",
    untitled: "Untitled",
    noMethods: "No payment methods yet",
    unavailable: {
      paused: "This link is paused.",
      expired: "This link has expired.",
      use_limit_reached: "This link has reached its limit.",
      no_methods_available: "No way to pay yet. Add a method.",
    } satisfies Record<UnavailableReason, string>,
    serverTotalPending: "Total after save",
  },
} as const;

export function methodLabel(m: { method: PayMethod; chain?: string | null; asset?: string | null }): string {
  if (m.method === "crypto") return [m.asset, m.chain ? `on ${m.chain}` : ""].filter(Boolean).join(" ") || "Crypto";
  return LINKS_COPY.fields.methodNames[m.method];
}
