"use client";

/**
 * Per-wallet address pool page.
 *
 * Shows the paginated, filterable list of addresses generated by a single
 * HD wallet. The wallet summary (name, family, counts) is pulled from the
 * cached wallets list so we avoid a second round-trip.
 *
 * Backed by GET /wallets and GET /wallets/:id/addresses.
 */
import { use, useMemo, useState } from "react";
import Link from "next/link";
import {
  ArrowLeft,
  Check,
  ChevronRight,
  Copy,
  MapPin,
} from "lucide-react";
import { toast } from "sonner";
import {
  useWalletAddresses,
  useWalletsList,
} from "@/lib/query/hooks/use-wallets";
import type {
  AddressPoolItem,
  Wallet,
} from "@/lib/query/hooks/use-wallets";
import { ErrorState, EmptyState } from "@/components/ui/states";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { StatusBadge } from "@/components/ui/status-badge";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { BlockchainIcon } from "@/components/blockchain-icon";
import { cn } from "@/lib/utils";
import type { BlockchainNetwork } from "@/lib/types";

const PAGE_SIZE = 20;

const STATUS_TABS = [
  { value: "all", label: "All" },
  { value: "available", label: "Available" },
  { value: "used", label: "Used" },
  { value: "locked", label: "Locked" },
] as const;

type StatusTabValue = (typeof STATUS_TABS)[number]["value"];

/* ── Family → display network (mirror of wallets/page.tsx) ── */

const FAMILY_NETWORK: Record<string, BlockchainNetwork> = {
  evm: "ethereum",
  eth_family: "ethereum",
  btc: "bitcoin",
  btc_family: "bitcoin",
  trx: "tron",
  trx_family: "tron",
};

function networkFor(wallet: Wallet | undefined): BlockchainNetwork {
  if (!wallet) return "ethereum";
  const candidates = [
    wallet.blockchainFamily?.code,
    wallet.blockchainFamily?.family,
    wallet.blockchainFamily?.name,
  ];
  for (const candidate of candidates) {
    if (!candidate) continue;
    const match = FAMILY_NETWORK[candidate.toLowerCase()];
    if (match) return match;
  }
  return "ethereum";
}

/* ── Page component ───────────────────────────────────── */

export default function WalletAddressesPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id: rawId } = use(params);
  const walletID = Number(rawId);

  const [tab, setTab] = useState<StatusTabValue>("all");
  const [offset, setOffset] = useState(0);

  const {
    data: walletsData,
    isLoading: walletsLoading,
  } = useWalletsList();

  const wallet = useMemo(
    () => walletsData?.wallets.find((w) => w.id === walletID),
    [walletsData, walletID]
  );

  const queryParams = {
    status: tab === "all" ? undefined : tab,
    limit: PAGE_SIZE,
    offset,
  };
  const {
    data: addressesData,
    isLoading: addressesLoading,
    error,
    refetch,
  } = useWalletAddresses(
    Number.isFinite(walletID) && walletID > 0 ? walletID : undefined,
    queryParams
  );

  const addresses = addressesData?.addresses ?? [];
  const total = addressesData?.total ?? 0;

  if (!Number.isFinite(walletID) || walletID <= 0) {
    return (
      <div className="space-y-6">
        <Breadcrumbs walletName="Invalid wallet" />
        <ErrorState message={`Invalid wallet id: ${rawId}`} />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <Breadcrumbs walletName={wallet?.name ?? "Wallet"} />

      {/* Back + header */}
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div className="flex items-start gap-3">
          <Link href="/dashboard/wallets">
            <Button
              variant="outline"
              size="sm"
              className="h-9 w-9 p-0"
              aria-label="Back to wallets"
            >
              <ArrowLeft className="size-4" />
            </Button>
          </Link>
          <div>
            <h1 className="text-xl font-bold tracking-tight">
              {walletsLoading
                ? "Loading wallet…"
                : wallet?.name ?? `Wallet #${walletID}`}
            </h1>
            <p className="text-[13px] text-muted-foreground mt-0.5">
              Pre-generated address pool for this HD wallet
            </p>
          </div>
        </div>
      </div>

      {/* Wallet summary card */}
      <WalletSummary wallet={wallet} isLoading={walletsLoading} />

      {/* Filter tabs */}
      <Tabs
        value={tab}
        onValueChange={(v) => {
          setTab(v as StatusTabValue);
          setOffset(0);
        }}
      >
        <TabsList className="h-auto flex-wrap">
          {STATUS_TABS.map((t) => (
            <TabsTrigger key={t.value} value={t.value} className="text-xs">
              {t.label}
            </TabsTrigger>
          ))}
        </TabsList>
      </Tabs>

      {/* Error */}
      {error ? (
        <ErrorState message={error.message} retry={() => refetch()} />
      ) : null}

      {/* Table */}
      {addressesLoading ? (
        <div className="space-y-2">
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className="h-12 w-full rounded-lg" />
          ))}
        </div>
      ) : addresses.length > 0 ? (
        <Card className="border-border shadow-sm overflow-hidden">
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow className="border-border hover:bg-transparent">
                  <TableHead className="pm-label pl-6">Address</TableHead>
                  <TableHead className="pm-label">Path Index</TableHead>
                  <TableHead className="pm-label">Status</TableHead>
                  <TableHead className="pm-label text-right pr-6">
                    Created
                  </TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {addresses.map((addr) => (
                  <AddressRow key={addr.id} address={addr} />
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      ) : !error ? (
        <EmptyState
          title="No addresses yet"
          description={
            tab === "all"
              ? "This wallet has no addresses in its pool."
              : `No ${tab} addresses in this pool.`
          }
          icon={<MapPin className="size-5" />}
        />
      ) : null}

      {/* Pagination */}
      {total > PAGE_SIZE ? (
        <div className="flex items-center justify-between">
          <p className="text-[13px] text-muted-foreground tabular-nums">
            Showing {offset + 1}&ndash;{Math.min(offset + PAGE_SIZE, total)} of{" "}
            {total}
          </p>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              disabled={offset === 0}
              onClick={() => setOffset(Math.max(0, offset - PAGE_SIZE))}
            >
              Previous
            </Button>
            <Button
              variant="outline"
              size="sm"
              disabled={offset + PAGE_SIZE >= total}
              onClick={() => setOffset(offset + PAGE_SIZE)}
            >
              Next
            </Button>
          </div>
        </div>
      ) : null}
    </div>
  );
}

/* ── Breadcrumbs ──────────────────────────────────────── */

function Breadcrumbs({ walletName }: { walletName: string }) {
  return (
    <nav className="flex items-center gap-1.5 text-[13px] text-muted-foreground">
      <Link
        href="/dashboard"
        className="hover:text-foreground transition-colors"
      >
        Dashboard
      </Link>
      <ChevronRight className="size-3.5" />
      <Link
        href="/dashboard/wallets"
        className="hover:text-foreground transition-colors"
      >
        Wallets
      </Link>
      <ChevronRight className="size-3.5" />
      <span className="text-foreground font-medium truncate max-w-[240px]">
        {walletName}
      </span>
    </nav>
  );
}

/* ── Wallet summary card ──────────────────────────────── */

function WalletSummary({
  wallet,
  isLoading,
}: {
  wallet: Wallet | undefined;
  isLoading: boolean;
}) {
  if (isLoading) {
    return <Skeleton className="h-24 rounded-xl" />;
  }
  if (!wallet) {
    return null;
  }

  const network = networkFor(wallet);

  return (
    <Card className="border-border shadow-sm">
      <CardContent className="p-5">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="flex items-center gap-3 min-w-0">
            <BlockchainIcon blockchain={network} size="lg" />
            <div className="min-w-0">
              <div className="flex items-center gap-2">
                <h2 className="text-[14px] font-semibold truncate">
                  {wallet.name}
                </h2>
                <Badge variant="outline">{wallet.kind.toUpperCase()}</Badge>
                <StatusBadge status={wallet.status} />
              </div>
              <p className="pm-label mt-0.5">
                {wallet.blockchainFamily?.name ?? "Blockchain family"} ·{" "}
                {wallet.blockchainFamily?.code ?? "—"}
              </p>
              {wallet.blockchainFamily?.path ? (
                <p className="mt-1 font-mono text-[11px] text-muted-foreground">
                  {wallet.blockchainFamily.path}
                </p>
              ) : null}
            </div>
          </div>
          <div className="text-right">
            <div className="pm-label">Total addresses</div>
            <div className="text-2xl font-bold tabular-nums">
              {wallet.addressCount.toLocaleString()}
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

/* ── Address row (with inline copy) ───────────────────── */

function AddressRow({ address }: { address: AddressPoolItem }) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(address.address);
      setCopied(true);
      toast.success("Address copied to clipboard");
      setTimeout(() => setCopied(false), 1600);
    } catch {
      toast.error("Failed to copy address");
    }
  }

  return (
    <TableRow className="border-border/60 hover:bg-muted/30">
      <TableCell className="pl-6">
        <button
          type="button"
          onClick={handleCopy}
          className={cn(
            "group inline-flex items-center gap-2 font-mono text-[12px] text-foreground",
            "hover:text-[var(--pm-primary)] transition-colors"
          )}
          aria-label="Copy address"
          title={address.address}
        >
          <span className="truncate max-w-[280px]">
            {truncateMiddle(address.address, 10, 8)}
          </span>
          {copied ? (
            <Check className="size-3.5 shrink-0 text-emerald-400" />
          ) : (
            <Copy className="size-3.5 shrink-0 opacity-40 group-hover:opacity-100" />
          )}
        </button>
      </TableCell>
      <TableCell className="font-mono text-[12px] text-muted-foreground tabular-nums">
        {address.pathIndex}
      </TableCell>
      <TableCell>
        <StatusBadge status={address.status} />
      </TableCell>
      <TableCell className="text-right pr-6 text-[12px] text-muted-foreground">
        {new Date(address.createdAt).toLocaleString()}
      </TableCell>
    </TableRow>
  );
}

function truncateMiddle(value: string, head: number, tail: number): string {
  if (value.length <= head + tail + 3) return value;
  return `${value.slice(0, head)}…${value.slice(-tail)}`;
}
